config/routes.rb
Gmaps::Application.routes.draw do
  resources :characters

  root :to => 'characters#index'

end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :string(255)
#  latitude   :string(255)
#  longitude  :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  gmaps      :boolean
#

class Character < ActiveRecord::Base
  attr_accessible :name, :address, :latitude, :longitude
  acts_as_gmappable


  	def gmaps4rails_address
		#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
  		#"#{self.street}, #{self.city}, #{self.country}"
  		address
	end


            
  def gmaps4rails_marker_picture
  {
    "rich_marker" =>  "<div class='my-marker'>
      <img height='30' width='30' src='https://secure.gravatar.com/avatar/ankithbti007@gmail.com'/></div>"
  }
  end

  
	# def gmaps4rails_infowindow
 #      "<h1>#{name}</h1>"
 #  end

  # def gmaps4rails_title
  #     # add here whatever text you desire
  #     "<h4>Title</h4>"
  # end

  # def gmaps4rails_marker_picture
  #   {
  #    "picture" => "/images/#{name}.png",
  #    "width" => 20,
  #    "height" => 20,
  #    "marker_anchor" => [ 5, 10],
  #    "shadow_picture" => "/images/morgan.png" ,
  #    "shadow_width" => "110",
  #    "shadow_height" => "110",
  #    "shadow_anchor" => [5, 10],
  #   }
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
    # @json = Character.all.to_gmaps4rails
    # @json = Character.all.to_gmaps4rails do |character, marker|
    #   #marker.infowindow render_to_string(:partial => "/users/my_template", :locals => { :object => character})
    #   marker.picture({
    #                   :picture => "rails.png",
    #                   :width   => 32,
    #                   :height  => 32
    #                  })
    #   marker.title   "i'm the #{character.name}"
    #   marker.sidebar "i'm the sidebar"
    #   marker.json({ :id => character.id })
    # end
    @json = Character.all.to_gmaps4rails do |character, marker|
      marker.json({ :id => character.id })
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(params[:character])
    if @character.save
      redirect_to @character, :notice => "Successfully created character."
    else
      render :action => 'new'
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:character])
      redirect_to @character, :notice  => "Successfully updated character."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_url, :notice => "Successfully destroyed character."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
		def full_title(page_title)
		base_title = "Demo of GMaps for Rails"
		@page_title = page_title
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
		end

		def check_null(str)
			if str.empty?
				true
			else
				false
			end
		end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for @character, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                characters_path, :class => 'btn' %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/index.html.erb
<% provide(:title, "Character")%>
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= link_to character.id, character_path(character) %></td>
        <td><%= character.name %></td>
        <td><%= character.address %></td>
        <td><%= character.latitude %></td>
        <td><%= character.longitude %></td>
        <td><%=l character.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_character_path(character), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      character_path(character),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_character_path,
            :class => 'btn btn-primary' %>
            
            <%= gmaps("markers" => {"data" => @json, "options" => {"rich_marker" => true } }) %>

app/views/characters/new.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/show.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @character.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @character.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @character.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @character.longitude %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              characters_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_character_path(@character), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              character_path(@character),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :scripts %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-error">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li>* <%= msg %></li>
<% end %>
</ul>
</div>
<% end %>